In [1]:
import pandas as pd
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier

In [2]:
iris = sns.load_dataset("iris")

In [3]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
iris.species.value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

## Features and Label

In [5]:
X = iris.iloc[:, :4]
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [6]:
y = iris.iloc[:, -1]
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [7]:
y.astype('category').cat.codes

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Length: 150, dtype: int8

## Data Splitting

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
len(y_test)

45

## Fitting

In [10]:
knn = KNeighborsClassifier()

In [11]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

## Predicting

In [12]:
predictions = knn.predict(X_test)
pd.DataFrame({'actual': y_test, 'predictions': predictions})

         actual predictions
77   versicolor   virginica
94   versicolor  versicolor
76   versicolor  versicolor
12       setosa      setosa
51   versicolor  versicolor
118   virginica   virginica
61   versicolor  versicolor
17       setosa      setosa
109   virginica   virginica
27       setosa      setosa
60   versicolor  versicolor
141   virginica   virginica
93   versicolor  versicolor
68   versicolor  versicolor
31       setosa      setosa
90   versicolor  versicolor
13       setosa      setosa
111   virginica   virginica
126   virginica   virginica
140   virginica   virginica
53   versicolor  versicolor
105   virginica   virginica
58   versicolor  versicolor
52   versicolor  versicolor
39       setosa      setosa
100   virginica   virginica
63   versicolor  versicolor
43       setosa      setosa
99   versicolor  versicolor
16       setosa      setosa
128   virginica   virginica
47       setosa      setosa
55   versicolor  versicolor
110   virginica   virginica
37       setosa      setosa
57   versicolor  versicolor
32       setosa      setosa
78   versicolor  versicolor
10       setosa      setosa
84   versicolor  versicolor
143   virginica   virginica
46       setosa      setosa
28       setosa      setosa
132   virginica   virginica
115   virginica   virginica

## Evaluation

In [13]:
(predictions == y_test).sum()/len(y_test)*100

97.77777777777777

In [14]:
knn.score(X_test, y_test)

0.9777777777777777